### ISSUE TITLE
Doesn't handle negatives

### ISSUE THREAD

**Issue by kylelin47** [kylelin47/COP-Project#12]
p. important, haven't thought how to fix it

When parser sees -2, does it create a multexpression with sign - and vector containing smart int 2?

**Comment by alexs10** [comment]
Yes it does what you said. I changed some things though. Each is going to have an internal sign (most of them already do). They have an extra constructor with a (char sign) option to set the sign manually, otherwise the sign is '+'.

**Comment by alexs10** [comment]
When printing, each end number will only print their sign if it is negetive. MultExpression always prints its sign. So It works right now for the SumExpression( MultExpression( other numbers)) approach but not when it gets simplified. But that is easy enough for me to fix later in the SumExpression toString()
