### ISSUE TITLE
Doesn't divide

### ISSUE THREAD

**Issue by kylelin47** [kylelin47/COP-Project#13]
Everything

Does parser correctly place things in numerator/denominator vectors?

**Comment by cphazen** [comment]
Sorry, didn't mean to close that.

**Comment by alexs10** [comment]
Ya it does. Or at least it should. if it is printing '/' then it is printing from the denominator

**Comment by kylelin47** [comment]
toString() doesn't print '/'. Pretty sure it's not properly in the denominator.
