### ISSUE TITLE
Add() Multiply() and Divide() methods

### ISSUE THREAD

**Issue by alexs10** [kylelin47/COP-Project#16]
Now that we have signs implemented. Your add() method should realize if the term it is being added to cancels it out. In that case return a SmartInteger(0). Also try to make sure what ever you are returning has the correct sign. Ex: if you add Pi and Pi and both of their getSigns() == '-', then return a MultExpression ( SmartInteger(2) , Pi(), '-') which is -2pi.

**Comment by cphazen** [comment]
Looking over MultExpression constructors-- Wouldn't MultExpression(SmartInteger(2), Pi(), '-') create -2/pi? Or was that changed?

**Comment by kylelin47** [comment]
It should have that constructor
I think alex might've overwritten it on accident

Yeah he did, adding them back
