### ISSUE TITLE
TO DO:

### ISSUE THREAD

**Issue by kylelin47** [kylelin47/COP-Project#20]
1. Menu
   - Carlos is working on this
2. Exceptions for improper number creation
3. ESPECIALLY FOR RADICAL. I ASSUME IT ALWAYS WILL EVALUATE TO A REAL NUMBER IN ITS SIMPLIFY
4. History/'ans' keyword
5. FOIL

add to this list what I missed and say what you want to do

**Comment by alexs10** [comment]
Just fixed the negative issue. There is also a global var history where we can store strings.Im going to work on multiply and divide for radicals now.

**Comment by alexs10** [comment]
The early classes addition/multiplication has been solved. All that is left is e, pi, and maybe exponents. Radical division is also done. Im going to work on exceptions.
