### ISSUE TITLE
Meeting up

### ISSUE THREAD

**Issue by kylelin47** [kylelin47/COP-Project#24]
I think we should meet up today and push out a product with a fully functional menu that is gradable. Any suggestions for time?

**Comment by alexs10** [comment]
I can go any time after 3pm.

**Comment by ccast1115** [comment]
I can meet up around 430/5

**Comment by cphazen** [comment]
I am unable to meet up today

**Comment by alexs10** [comment]
Ok lets meet at 4:30 if  everyone is ok with that.

**Comment by kylelin47** [comment]
sure
