### ISSUE TITLE
pi-pi = 2pi?

### ISSUE THREAD

**Issue by alexs10** [kylelin47/COP-Project#30]

**Comment by kylelin47** [comment]
shows as 0 on mine.

**Comment by alexs10** [comment]
is yours uploaded?

**Comment by alexs10** [comment]
Push your working commit, im just going to clone that and work from their. I have a lot of things not working.

**Comment by kylelin47** [comment]
Force pushed.

**Comment by kylelin47** [comment]
Everything is working except for inconsistent reading of integers i.e Int(-8, -) is = 8 or -8
