### ISSUE TITLE
WHAT I'M UP TO

### ISSUE THREAD

**Issue by kylelin47** [kylelin47/COP-Project#32]
```
VERY SOON I WILL PUSH A COMMIT THAT IS AS CLOSE TO PERFECT STABILITY WISE AS I CAN MAKE IT. WORK OFF THIS COMMIT AND ADD HISTORY, THROWS.

THEN, MAKE INTEGERS CONSISTENT: GETSIGN() WILL JUST RETURN THE SIGN OF THE VALUE. THE VALUE IS WHAT MATTERS AND SHOULD NOT CHANGE DEPENDING ON THE SIGN.

FINALLY, WE CAN WORK ON MAKING THE OUTPUT PRETTIER. FOR EXAMPLE, 1/sqrt:2 = sqrt:2/2. REMOVE +0, *1, UNNECESSARY SIGNS
```

ALSO, WE NEED TO SAY IN OUR HELP MENU THAT WE DON'T ACCEPT 3rt:-8 AND THAT IT NEEDS TO BE 3rt:(-8)

**Comment by alexs10** [comment]
I fixed the integer thing.

**Comment by cphazen** [comment]
I'll do printing exceptions when I get out of class (6/6:30ish) 
I can also look into history if no one gets to it beforehand

**Comment by kylelin47** [comment]
also, keyword ans. Just passing in the string might not work as we have stuff like -- that our parser won't accept. most recent answer needs to be the original AbstractNumber that was returned and should be added through the parser and the rest can be strings.

**Comment by alexs10** [comment]
ans should pass the original input, which is parseable.
