### ISSUE TITLE
Their are some redundant -1 getting added to multExpression

### ISSUE THREAD

**Issue by alexs10** [kylelin47/COP-Project#33]
we should just change the sign

**Comment by kylelin47** [comment]
0k

also, there's an issue with pi. e - e = 0 but pi - pi does not. id look into it but i have class

Yeah, it's only in pi. (3e-2)(3e+2) works correctly. so just fix that and our sign issues should be gone.

we can remove +0s from sumE als0

**Comment by alexs10** [comment]
(pi-e)(pi+e) screws up. But its probably the same reason

**Comment by alexs10** [comment]
I think whats happening is that when the multExpression simplifies down to a pi (or log) it drops the negetive.

**Comment by kylelin47** [comment]
sounds about right
can you fix it or should i
it just needs to pass in its own sign probably

**Comment by kylelin47** [comment]
actually (3pi+2)(3pi-2) is working now

**Comment by alexs10** [comment]
Confirmed, the issue is when simplifying. If I create a pi and negative pi manually, they add to zero. It is also not the parser. I am not sure how your simpllify functions work, so you should fix this.

**Comment by kylelin47** [comment]
actually a lot is working right

**Comment by kylelin47** [comment]
integers interact fine but (pi-e)(pi+e) doesn't

sounds like edge case 2 me

**Comment by alexs10** [comment]
(2-3e)(2+3e) fails
it adds an extra 12e. Which means it created an 6e when simplifying instead of a -6e. Im going to redo the multiplication on e, I alos think logs fail at this too.

**Comment by kylelin47** [comment]
yeah see if there's mistakes there.
most likely it's just i don;t pass in the sign when creating new stuff

**Comment by kylelin47** [comment]
problem is i have no idea how signs work

**Comment by alexs10** [comment]
Thats what I am guessing right now too. Besides that and dividing with radicals, everything is working great.

**Comment by alexs10** [comment]
When you create the pi you return, just say new Pi(sign) to set it equal to the sign of the mult expression.

**Comment by kylelin47** [comment]
i never create anything

**Comment by kylelin47** [comment]
i know. if i return numbr and my sign is negative i multiply it by -1

**Comment by kylelin47** [comment]
-6e - 6e = 12e

once that's fixed foil will be fixed.

**Comment by kylelin47** [comment]
in here in multexp simplify:
    if (numerator.size() == 1 || denominator.size() == 1)
    {
        if (numerator.size() == 0)
        {
            return denominator[0];
        }
        if (denominator.size() == 0)
        {
            return numerator[0];
        }
    }
have it return numerator[0] multiplied by negative one if own sign is negative and see if it fixes it.

don't worry about return denominator[0]. in theory that should never happen and if it does the result will be completely invalid, its just there to try and stop crashing

**Comment by alexs10** [comment]
I will get to that after I am done with radical division.
