### ISSUE TITLE
Have we submitted our project again?

### ISSUE THREAD

**Issue by alexs10** [kylelin47/COP-Project#37]

**Comment by cphazen** [comment]
Doesn't look like it.

**Comment by alexs10** [comment]
Do you want to submit it or should I? I need 0.14 more points for an A.

**Comment by cphazen** [comment]
You can go ahead.

**Comment by kylelin47** [comment]
If you want, you could probably go to our TA's office hours and argue for a higher initial submission grade - I think she graded the wrong submission because of the multiple re-submissions that I did. Might be able to get you out of taking the final.

**Comment by kylelin47** [comment]
We have an updated project stage 2 grade so check that before taking the final

**Comment by alexs10** [comment]
Perfect. I got out the final. Good work on the project everyone.
